sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t joeygibson/terraform .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push joeygibson/terraform

script:
  - /bin/true

